apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "mongodb-dam.fullname" . }}-observer
  labels:
    {{- include "mongodb-dam.labels" . | nindent 4 }}
    app.kubernetes.io/component: observer
automountServiceAccountToken: false
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "mongodb-dam.fullname" . }}-outpost
  labels:
    {{- include "mongodb-dam.labels" . | nindent 4 }}
    app.kubernetes.io/component: outpost
automountServiceAccountToken: true
